# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [
  {
      :name => "redis1",
      :eth1 => "192.168.100.21",
      :mem => "4096",
      :cpu => "4",
      :hostport=>6379
  },
  {
    :name => "redis2",
    :eth1 => "192.168.100.22",
    :mem => "4096",
    :cpu => "4",
    :hostport=>6380
  },
  {
    :name => "redis3",
    :eth1 => "192.168.100.23",
    :mem => "4096",
    :cpu => "4",
    :hostport=>6381
  }
]  

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  # config.vm.box = "bento/ubuntu-20.04" # for testing

  # Optional, SMB folder sharing
  # If you wish to disable SMB share
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Configure SMB folder sharing
  # config.vm.synced_folder '.', '/vagrant', {
  #   type: 'smb', mount_options: ['vers=3.0'],
  #   smb_username: ENV['VAGRANT_SMB_USERNAME'],
  #   smb_password: ENV['VAGRANT_SMB_PASSWORD']
  # }
    
  boxes.each do |opts|
    config.vm.define opts[:name] do |node|

      node.vm.network "public_network", bridge: "BRIDGE"
      node.vm.synced_folder ".", "/vagrant_data", disabled: true
      node.vm.provider "hyperv"
      node.vm.hostname = opts[:name]

      node.vm.provider "hyperv" do |h|
          h.enable_virtualization_extensions = false
          h.linked_clone = true
          h.vmname = opts[:name]
          h.maxmemory = opts[:mem]
          h.memory = opts[:mem]
          h.cpus = opts[:cpu]
      end
      config.vm.provision "ansible" do |a|
        a.verbose = "v"
        a.playbook = "playbook.yml"
      end
    end
  end
end