---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=America/Mexico_City
      - PLEX_CLAIM=
    volumes:
      - ./library:/config
      - ./tvseries:/tv
      - ./movies:/movies
    restart: unless-stopped