---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
      - TRANSMISSION_WEB_HOME=/combustion-release/
    volumes:
      - ~/docker/transmission/config:/config
      - ~/docker/transmission/downloads:/downloads
      - ~/docker/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped