---
services:
  bind9:
    container_name: bind9
    image: ubuntu/bind9:9.18-23.10_edge
    # image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=America/Mexico_City
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/etc/bind/
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    restart: unless-stopped